//该方法主要是写了测试Writable数据流的一些性质

const ToFileStream = require('./toFileStream.js');
const tfs = new ToFileStream();


const path = require('path')
//console.log(path.dirname())
// console.log(path.dirname("file1.txt"))
// console.log(path.dirname("./var/file1.txt"))
tfs.write({path: "file1.txt", content: "Hello"});
console.log("1");
tfs.write({path: "file2.txt", content: "Node.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvNode.js吧vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"});
console.log("2");
tfs.write({path: "file3.txt", content: "Streams"});
console.log("3");
tfs.end(() => console.log("All files created"));
